#!/bin/bash
logger --tag "deursoos" 'Reprogramming the door controller'
/opt/deursysteem/teensy_loader_cli -mmcu=atmega32u4 -w /opt/deursysteem/serial.hex
logger --tag "deursoos" 'Completed reprogramming of the door'
