#!/bin/bash
logger "Resetting system to ensure connectivity to the reader"
logger 'Stopping pcscd service'
service pcscd stop

USB=`lsusb -d 1a40:0101`
regex="Bus ([0-9]{3}) Device ([0-9]{3})"

if [[ $USB =~ $regex ]]; then
    logger "Found USB-scanner at Bus ${BASH_REMATCH[1]} Device ${BASH_REMATCH[2]}. Resetting.."
    /opt/deursysteem/usbreset /dev/bus/usb/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
    logger "USB-scanner reset succesful"
else
    logger "Couldn't find the USB-scanner"
fi

logger 'Restarting pcscd service'
service pcscd start
