#!/bin/bash
logger "Resetting system to ensure connectivity to the reader"

USB=`lsusb -d 1a40:0101`
regex="Bus ([0-9]{3}) Device ([0-9]{3})"

if [[ $USB =~ $regex ]]; then
    logger "Found USB-hub at Bus ${BASH_REMATCH[1]} Device ${BASH_REMATCH[2]}. Resetting.."
    ./usbreset /dev/bus/usb/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
    logger "Found USB-hub at Bus ${BASH_REMATCH[3]} Device ${BASH_REMATCH[4]}. Resetting.."
    ./usbreset /dev/bus/usb/${BASH_REMATCH[3]}/${BASH_REMATCH[4]}
else
    logger "Couldn't find the USB-scanner"
fi

logger "Rebooting system"
reboot
