#!/bin/bash
echo Starting...
sleep 1s
logger Started scanning
echo Started scanning
while true
do
/home/deursysteem/scanner | (
	while true
	do
		read id || exit
		logger Found $id, authenticating...
		php /home/deursysteem/authenticate.php $id
	done
	) 
sleep 1s
done
