#!/bin/bash
echo Starting...
sleep 1s
logger Started scanning
echo Started scanning
while true; do
    READ=`/usr/bin/php /home/deursysteem/read.php`
    if [ $? -eq 0 ]; then
        echo "Got card, attempting authentication"
        php /home/deursysteem/authenticate.php $READ
    else
        echo "Can't connect to scanner. Waiting one minute before retrying"
        sleep 60s
    fi
done
